FROM node:18-alpine AS builder

ARG BACKEND_URL

WORKDIR /app

COPY . .
RUN npm install
WORKDIR /app/client
ENV VITE_BACKEND_URL=${BACKEND_URL}
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/client/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]