FROM node:18-alpine as builder

WORKDIR /app

COPY . .
RUN npm install
WORKDIR /app/client
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/client/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]